# Generated by Django 5.0 on 2023-12-20 06:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.UUIDField(blank=True, help_text='User Id who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='User Id who updated this record.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time at which this record is created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time at which this record is last updated.', null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.UUIDField(blank=True, help_text='User Id who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='User Id who updated this record.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time at which this record is created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time at which this record is last updated.', null=True)),
                ('name', models.CharField(max_length=225, unique=True)),
                ('state_code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='app_dashboard.country')),
            ],
            options={
                'verbose_name': 'Dashboard - State Details',
                'verbose_name_plural': 'Dashboard - State Details',
                'unique_together': {('country', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.UUIDField(blank=True, help_text='User Id who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='User Id who updated this record.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time at which this record is created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time at which this record is last updated.', null=True)),
                ('name', models.CharField(max_length=225)),
                ('pin_code', models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]{6}$')])),
                ('is_active', models.BooleanField(default=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='app_dashboard.states')),
            ],
            options={
                'verbose_name': 'Dashboard - City Details',
                'verbose_name_plural': 'Dashboard - City Details',
                'unique_together': {('state', 'name')},
            },
        ),
    ]
