# Generated by Django 5.0 on 2023-12-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Dashboard - Country Details', 'verbose_name_plural': 'Dashboard - Country Details'},
        ),
        migrations.AddField(
            model_name='country',
            name='iso2_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='iso3_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
