# Generated by Django 5.0 on 2023-12-15 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dashboard', '0002_rename_city_cities_name_rename_state_states_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='pin_code',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]{6}$')]),
        ),
    ]
