# Generated by Django 5.0 on 2023-12-19 05:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GstDetail',
            fields=[
                ('created_by', models.UUIDField(blank=True, help_text='User Id who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='User Id who updated this record.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time at which this record is created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time at which this record is last updated.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_gst_number', models.CharField(max_length=16, unique=True)),
                ('legal_name_of_business', models.CharField(blank=True, max_length=225, null=True)),
                ('state_jurisdiction', models.CharField(blank=True, max_length=225, null=True)),
                ('state_jurisdiction_code', models.CharField(blank=True, max_length=225, null=True)),
                ('date_of_registration', models.DateField(blank=True, null=True)),
                ('constitution_of_business', models.CharField(blank=True, max_length=225, null=True)),
                ('taxpayer_type', models.CharField(blank=True, max_length=225, null=True)),
                ('nature_of_business_activity', models.CharField(blank=True, max_length=700, null=True)),
                ('gstn_status', models.CharField(blank=True, max_length=225, null=True)),
                ('last_updated_date', models.CharField(blank=True, max_length=225, null=True)),
                ('trade_name', models.CharField(blank=True, max_length=700, null=True)),
                ('additional_place_of_business_address', models.CharField(blank=True, max_length=225, null=True)),
                ('building_name', models.CharField(blank=True, max_length=225, null=True)),
                ('street', models.CharField(blank=True, max_length=225, null=True)),
                ('location', models.CharField(blank=True, max_length=225, null=True)),
                ('state_name', models.CharField(blank=True, max_length=225, null=True)),
                ('floor_nbr', models.CharField(blank=True, max_length=225, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=6, null=True)),
                ('pricipal_place_of_business_address', models.CharField(blank=True, max_length=225, null=True)),
                ('state_name_repeat', models.CharField(blank=True, max_length=225, null=True)),
                ('pin_code_repeat', models.CharField(blank=True, max_length=6, null=True)),
                ('response_json', models.JSONField(blank=True, default=dict, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('inactive_reason', models.CharField(blank=True, max_length=225, null=True)),
                ('user', models.OneToOneField(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_gst_detail', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification - GST Details',
                'verbose_name_plural': 'Verification - GST Details',
            },
        ),
    ]
