# Generated by Django 5.0 on 2023-12-15 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gstdetail',
            name='inactive_reason',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='gstdetail',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
