# Generated by Django 5.0 on 2023-12-15 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_verification', '0002_gstdetail_inactive_reason_gstdetail_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gstdetail',
            options={'verbose_name': 'Verification - GST Details', 'verbose_name_plural': 'Verification - GST Details'},
        ),
    ]
