# Generated by Django 5.0 on 2023-12-26 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_verification', '0005_alter_representativedetail_representative_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='representativedetail',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_representative_detail', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
