# Generated by Django 5.0 on 2023-12-26 07:24

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_verification', '0006_alter_representativedetail_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankVerification',
            fields=[
                ('created_by', models.UUIDField(blank=True, help_text='User Id who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='User Id who updated this record.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time at which this record is created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time at which this record is last updated.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_holder', models.CharField(max_length=255)),
                ('account_number', models.IntegerField(max_length=20, unique=True)),
                ('ifsc', models.CharField(max_length=11)),
                ('bank', models.CharField(blank=True, max_length=255, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('beneficiary_id', models.IntegerField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('mobile', models.IntegerField(default='', max_length=13)),
                ('utr', models.CharField(blank=True, max_length=50, null=True)),
                ('name_at_bank', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_deposited', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('reject_reason', models.TextField(blank=True, default='', null=True)),
                ('response_json', models.JSONField(blank=True, default=dict, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_Bank_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification - Bank Verification',
                'verbose_name_plural': 'Verification - Bank Verification',
            },
        ),
    ]
