# Generated by Django 5.0 on 2023-12-26 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_verification', '0008_remove_bankverification_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankverification',
            options={'verbose_name': 'Verification - Bank Detail', 'verbose_name_plural': 'Verification - Bank Detail'},
        ),
    ]
