# Generated by Django 5.0 on 2023-12-26 10:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_verification', '0009_alter_bankverification_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PanCinDetails',
            fields=[
                ('created_by', models.UUIDField(blank=True, help_text='User Id who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='User Id who updated this record.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time at which this record is created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time at which this record is last updated.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('cin', 'CIN'), ('pan', 'PAN')], max_length=5)),
                ('documnet_id', models.CharField(max_length=255)),
                ('response_json', models.JSONField(blank=True, default=dict, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('reject_reason', models.TextField(blank=True, default='', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_pan_cin_detail', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification - Pan Cin Detail',
                'verbose_name_plural': 'Verification - Pan Cin Detail',
                'unique_together': {('document_type', 'documnet_id')},
            },
        ),
    ]
