# Generated by Django 5.0 on 2023-12-28 11:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dashboard', '0002_alter_country_options_country_iso2_code_and_more'),
        ('app_verification', '0010_pancindetails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAddressDetail',
            fields=[
                ('created_by', models.UUIDField(blank=True, help_text='User Id who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='User Id who updated this record.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time at which this record is created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time at which this record is last updated.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_line_1', models.CharField(max_length=200)),
                ('address_line_2', models.CharField(max_length=200)),
                ('pin_code', models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]{6}$')])),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_dashboard.cities')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_dashboard.states')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_company_address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification - Company Address Detail',
                'verbose_name_plural': 'Verification - Company Address Detail',
            },
        ),
    ]
