# Generated by Django 5.0 on 2023-12-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_verification', '0011_companyaddressdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybasicdetail',
            name='about_brand',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
