# Generated by Django 5.0 on 2023-12-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_verification', '0012_companybasicdetail_about_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaddressdetail',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companyaddressdetail',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
