# Generated by Django 5.0 on 2024-01-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_verification', '0014_alter_bankverification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pancindetails',
            name='document_type',
            field=models.CharField(blank=True, choices=[('cin', 'CIN'), ('pan', 'PAN')], max_length=5, null=True),
        ),
    ]
