# Generated by Django 5.0 on 2024-01-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_verification', '0015_alter_pancindetails_document_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pancindetails',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='pancindetails',
            name='documnet_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
