# Generated by Django 5.0 on 2024-01-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_verification', '0016_alter_pancindetails_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaddressdetail',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
