# Generated by Django 5.0 on 2023-12-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
