# Generated by Django 5.0 on 2023-12-26 08:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_user_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSettings',
            fields=[
                ('created_by', models.UUIDField(blank=True, help_text='User Id who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='User Id who updated this record.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time at which this record is created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time at which this record is last updated.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receive_order_update_whatsapp', models.BooleanField(default=False)),
                ('receive_order_update_call', models.BooleanField(default=False)),
                ('receive_order_update_email', models.BooleanField(default=False)),
                ('receive_payment_update_whatsapp', models.BooleanField(default=False)),
                ('receive_payment_update_call', models.BooleanField(default=False)),
                ('receive_payment_update_email', models.BooleanField(default=False)),
                ('order_handling_time', models.CharField(choices=[('1-day', '1 Day'), ('2-day', '2 Day'), ('3-day', '3 Day'), ('4-day', '4 Day'), ('5-day', '5 Day'), ('6-day', '6 Day'), ('7-day', '7 Day'), ('8-day', '8 Day'), ('9-day', '9 Day'), ('10-day', '10 Day'), ('same-day', 'Same day'), ('more-than-10-days', 'More Than 10 Days')])),
                ('order_cutt_off_time', models.CharField(choices=[('00.00', '00.00'), ('00.30', '00.30'), ('01.00', '01.00'), ('01.30', '01.30'), ('02.00', '02.00'), ('02.30', '02.30'), ('03.00', '03.00'), ('03.30', '03.30'), ('04.00', '04.00'), ('04.30', '04.30'), ('05.00', '05.00'), ('05.30', '05.30'), ('06.00', '06.00'), ('06.30', '06.30'), ('07.00', '07.00'), ('07.30', '07.30'), ('08.00', '08.00'), ('08.30', '08.30'), ('09.00', '09.00'), ('09.30', '09.30'), ('10.00', '10.00'), ('10.30', '10.30'), ('11.00', '11.00'), ('11.30', '11.30'), ('12.00', '12.00'), ('12.30', '12.30'), ('13.00', '13.00'), ('13.30', '13.30'), ('14.00', '14.00'), ('14.30', '14.30'), ('15.00', '15.00'), ('15.30', '15.30'), ('16.00', '16.00'), ('16.30', '16.30'), ('17.00', '17.00'), ('17.30', '17.30'), ('18.00', '18.00'), ('18.30', '18.30'), ('19.00', '19.00'), ('19.30', '19.30'), ('20.00', '20.00'), ('20.30', '20.30'), ('21.00', '21.00'), ('21.30', '21.30'), ('22.00', '22.00'), ('22.30', '22.30'), ('23.00', '23.00'), ('23.30', '23.30')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_setting', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auth - Profile Settings',
                'verbose_name_plural': 'Auth - Profile Settings',
            },
        ),
    ]
