# Generated by Django 5.0 on 2023-12-26 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0006_pickupwarehouselocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PickUpWarehouseLocation',
        ),
    ]
