# Generated by Django 5.0 on 2024-01-23 06:43

import ckeditor.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('created_by', models.UUIDField(blank=True, help_text='User Id who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='User Id who updated this record.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time at which this record is created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time at which this record is last updated.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='pics')),
                ('author', models.CharField(default='theseventhsquare', max_length=60)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('Blog_type', models.CharField(choices=[('add_new_product', 'Add New Product'), ('platform_guide', 'Platform Guide'), ('tips_and_tricks', 'Trips And Tricks'), ('platform_updates', 'Platform Updates')], max_length=16, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
