# Generated by Django 5.0 on 2024-01-24 04:48

import ckeditor.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_context', '0002_alter_blog_image_alter_blog_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqMain',
            fields=[
                ('created_by', models.UUIDField(blank=True, help_text='User Id who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='User Id who updated this record.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time at which this record is created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time at which this record is last updated.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(blank=True, max_length=500, null=True)),
                ('answer', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('author', models.CharField(default='theseventhsquare', max_length=60)),
                ('tage_type', models.CharField(choices=[('getting_started', 'Getting Started'), ('manage_your_account', 'Manage your account'), ('adding_products', 'Adding Products'), ('processing_orders', 'Processing Orders'), ('pricing_payments', 'Pricing & Payments'), ('shipping_returns', 'Shipping & Returns'), ('advertising ', 'Advertising '), ('policy_security', 'Policy & Security'), ('enquiries', 'Enquiries'), ('disputes_resolution', 'Disputes & Resolution')], max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
