# Generated by Django 5.0 on 2023-12-26 10:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickUpWarehouseLocation',
            fields=[
                ('created_by', models.UUIDField(blank=True, help_text='User Id who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='User Id who updated this record.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time at which this record is created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time at which this record is last updated.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plot_no', models.TextField(blank=True, max_length=255, null=True)),
                ('location_name', models.TextField(blank=True, max_length=255, null=True)),
                ('street', models.TextField(blank=True, max_length=255, null=True)),
                ('city', models.TextField(blank=True, max_length=255, null=True)),
                ('state', models.TextField(blank=True, max_length=255, null=True)),
                ('landmark', models.TextField(blank=True, max_length=255, null=True)),
                ('pincode', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_pick_up_warehouse_location', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventory - Pickup warehouse Location',
                'verbose_name_plural': 'Inventory - Pickup warehouse Location',
            },
        ),
    ]
