# Generated by Django 5.0 on 2024-01-05 06:27

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_by', models.UUIDField(blank=True, help_text='User Id who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='User Id who updated this record.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time at which this record is created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time at which this record is last updated.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PriceStructure',
            fields=[
                ('created_by', models.UUIDField(blank=True, help_text='User Id who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='User Id who updated this record.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time at which this record is created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time at which this record is last updated.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sale_price', models.CharField(blank=True, max_length=100, null=True)),
                ('mpr', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_code', models.CharField(blank=True, max_length=100, null=True)),
                ('minimum_order_qunatity', models.CharField(blank=True, max_length=555, null=True)),
                ('minimum_order_qunatity_unit', models.CharField(blank=True, choices=[('piece', 'Piece'), ('bag', 'Bag'), ('metric_tonne', 'Metric Tonne'), ('kilogram', 'Kilogram'), ('cubic_foot', 'Cubic Foot'), ('square_foot', 'Square Foot'), ('cubic_meter', 'Cubic Meter'), ('meter', 'Meter'), ('set', 'Set'), ('litre', 'Litre'), ('foot', 'Foot'), ('bundle', 'Bundle'), ('square_meter', 'Square Meter')], max_length=555, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_by', models.UUIDField(blank=True, help_text='User Id who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='User Id who updated this record.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time at which this record is created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time at which this record is last updated.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_title', models.CharField(blank=True, max_length=150, null=True)),
                ('slug', models.SlugField(blank=True, max_length=150, null=True)),
                ('about_the_brand', models.CharField(blank=True, max_length=225, null=True)),
                ('product_brand', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=3500, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=8, null=True)),
                ('warranty', models.CharField(blank=True, choices=[('1-month', '1 month'), ('2-months', '2 months'), ('3-months', '3 months'), ('4-months', '4 months'), ('5-months', '5 months'), ('6-months', '6 months'), ('7-months', '7 months'), ('8-months', '8 months'), ('9-months', '9 months'), ('10-months', '10 months'), ('11-months', '11 months'), ('12-months', '12 months'), ('1-years', '1 years'), ('2-years', '2 years'), ('3-years', '3 years'), ('4-years', '4 years'), ('5-years', '5 years'), ('6-years', '6 years'), ('7-years', '7 years'), ('8-years', '8 years'), ('9-years', '9 years'), ('10-years', '10 years')], max_length=100, null=True)),
                ('guarantee', models.CharField(blank=True, choices=[('1-month', '1 month'), ('2-months', '2 months'), ('3-months', '3 months'), ('4-months', '4 months'), ('5-months', '5 months'), ('6-months', '6 months'), ('7-months', '7 months'), ('8-months', '8 months'), ('9-months', '9 months'), ('10-months', '10 months'), ('11-months', '11 months'), ('12-months', '12 months'), ('1-years', '1 years'), ('2-years', '2 years'), ('3-years', '3 years'), ('4-years', '4 years'), ('5-years', '5 years'), ('6-years', '6 years'), ('7-years', '7 years'), ('8-years', '8 years'), ('9-years', '9 years'), ('10-years', '10 years')], max_length=100, null=True)),
                ('material', models.CharField(blank=True, max_length=225, null=True)),
                ('product_belong_to', models.CharField(choices=[('amazon', 'Amazon'), ('flipkart', 'Flipkart'), ('seventhsq', 'Seventhsq')], default='seventhsq', max_length=125)),
                ('packaging_size', models.CharField(blank=True, max_length=555, null=True)),
                ('components_per_unit', models.CharField(blank=True, max_length=555, null=True)),
                ('product_handling', models.CharField(blank=True, max_length=500, null=True)),
                ('installation', models.CharField(blank=True, max_length=500, null=True)),
                ('storage', models.CharField(blank=True, max_length=500, null=True)),
                ('usage', models.CharField(blank=True, max_length=500, null=True)),
                ('serviced_regions', models.CharField(blank=True, choices=[('deliver_pan_india', 'I deliver PAN India'), ('deliver_to_specified_state_cities', 'I deliver to specified state / cities only')], max_length=255, null=True)),
                ('shipping_include', models.BooleanField(default=False)),
                ('product_has_variant', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductBelongDetails',
            fields=[
                ('created_by', models.UUIDField(blank=True, help_text='User Id who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='User Id who updated this record.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time at which this record is created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time at which this record is last updated.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_fetch_id', models.CharField(blank=True, max_length=225, null=True)),
                ('product_fetch_status', models.BooleanField(default=False)),
                ('product_fetch_json', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('created_by', models.UUIDField(blank=True, help_text='User Id who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='User Id who updated this record.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time at which this record is created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time at which this record is last updated.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('picture', models.FileField(blank=True, null=True, upload_to='picture')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('created_by', models.UUIDField(blank=True, help_text='User Id who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='User Id who updated this record.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time at which this record is created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time at which this record is last updated.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_type')),
                ('commission_type', models.CharField(choices=[('commission_percentage', 'Commision Percentage'), ('amount_per_unit', 'Amount Per Unit')], default='commission_percentage', max_length=25)),
                ('commission_value', models.IntegerField(blank=True, default=0)),
                ('returnable_product', models.BooleanField(default=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('created_by', models.UUIDField(blank=True, help_text='User Id who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='User Id who updated this record.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time at which this record is created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time at which this record is last updated.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price_on_request', models.BooleanField(default=False)),
                ('default_varient', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceRegions',
            fields=[
                ('created_by', models.UUIDField(blank=True, help_text='User Id who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='User Id who updated this record.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time at which this record is created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time at which this record is last updated.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serviced_regions_description', models.CharField(blank=True, default=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShippingDetails',
            fields=[
                ('created_by', models.UUIDField(blank=True, help_text='User Id who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='User Id who updated this record.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time at which this record is created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time at which this record is last updated.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_weight', models.CharField(blank=True, max_length=125, null=True)),
                ('product_weight_unit', models.CharField(blank=True, choices=[('gms', 'Gms'), ('kgs', 'Kilograms (Kgs)'), ('grams', 'Grams (Gms)'), ('lts', 'Liters (l)'), ('lbs', 'Pounds (lbs)'), ('oz', 'Ounce (oz)'), ('mt', 'Tonne (mt)')], max_length=125, null=True)),
                ('returnable_product', models.BooleanField(default=False)),
                ('return_policy', models.CharField(blank=True, default=True, max_length=555, null=True)),
                ('shipping_method', models.CharField(blank=True, choices=[('shipping_with_seventh_square', 'Shipping With Seventh Square'), ('self_shipping', 'Self Shipping')], max_length=100, null=True)),
                ('packed_box_dimensions_width', models.CharField(blank=True, max_length=100, null=True)),
                ('packed_box_dimensions_unit', models.CharField(blank=True, choices=[('feet', 'Feet (ft)'), ('centimeters', 'Centimeters (cm)'), ('meters', 'Meters (mt)'), ('inches', 'Inches'), ('millimeters', 'Millimeters (mm)')], max_length=100, null=True)),
                ('packed_box_dimensions_length', models.CharField(blank=True, max_length=100, null=True)),
                ('packed_box_dimensions_height', models.CharField(blank=True, max_length=100, null=True)),
                ('product_dimensions_length', models.CharField(blank=True, max_length=50, null=True)),
                ('product_dimensions_width', models.CharField(blank=True, max_length=50, null=True)),
                ('product_dimensions_height', models.CharField(blank=True, max_length=50, null=True)),
                ('product_dimensions_unit', models.FloatField(blank=True, choices=[('piece', 'Piece'), ('bag', 'Bag'), ('metric_tonne', 'Metric Tonne'), ('kilogram', 'Kilogram'), ('cubic_foot', 'Cubic Foot'), ('square_foot', 'Square Foot'), ('cubic_meter', 'Cubic Meter'), ('meter', 'Meter'), ('set', 'Set'), ('litre', 'Litre'), ('foot', 'Foot'), ('bundle', 'Bundle'), ('square_meter', 'Square Meter')], default=0.0, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PickUpWarehouseLocation',
            fields=[
                ('created_by', models.UUIDField(blank=True, help_text='User Id who created this record.', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='User Id who updated this record.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time at which this record is created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time at which this record is last updated.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plot_no', models.CharField(blank=True, max_length=255, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('landmark', models.TextField(blank=True, max_length=255, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]{6}$')])),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_dashboard.cities')),
            ],
            options={
                'verbose_name': 'Inventory - Pickup Warehouse Location',
                'verbose_name_plural': 'Inventory - Pickup Warehouse Location',
            },
        ),
    ]
