# Generated by Django 5.0 on 2024-01-05 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_dashboard', '0001_initial'),
        ('app_inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupwarehouselocation',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_warehouse_location', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pickupwarehouselocation',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_dashboard.states'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventory.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='country_of_origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dashboard.country'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_product', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productbelongdetails',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_belong_details', to='app_inventory.product'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='app_inventory.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventory.producttype'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variant', to='app_inventory.product'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variant_image', to='app_inventory.productvariant'),
        ),
        migrations.AddField(
            model_name='pricestructure',
            name='product_variant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_variant_price_structure', to='app_inventory.productvariant'),
        ),
        migrations.AddField(
            model_name='serviceregions',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dashboard.cities'),
        ),
        migrations.AddField(
            model_name='serviceregions',
            name='product_variant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_variant_service_regions', to='app_inventory.productvariant'),
        ),
        migrations.AddField(
            model_name='serviceregions',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dashboard.states'),
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='pick_up_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_pickup_location', to='app_inventory.pickupwarehouselocation'),
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='product_variant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_variant_shipping_details', to='app_inventory.productvariant'),
        ),
    ]
