# Generated by Django 5.0 on 2023-12-26 13:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dashboard', '0002_alter_country_options_country_iso2_code_and_more'),
        ('app_inventory', '0002_alter_pickupwarehouselocation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickupwarehouselocation',
            name='pincode',
        ),
        migrations.AddField(
            model_name='pickupwarehouselocation',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app_dashboard.cities'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pickupwarehouselocation',
            name='pin_code',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]{6}$')]),
        ),
        migrations.AddField(
            model_name='pickupwarehouselocation',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app_dashboard.states'),
            preserve_default=False,
        ),
    ]
