# Generated by Django 5.0 on 2024-01-06 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='default_varient',
            new_name='default_variant',
        ),
        migrations.RemoveField(
            model_name='pricestructure',
            name='minimum_order_qunatity',
        ),
        migrations.RemoveField(
            model_name='pricestructure',
            name='minimum_order_qunatity_unit',
        ),
        migrations.RemoveField(
            model_name='serviceregions',
            name='product_variant',
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_order_qunatity',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_order_qunatity_unit',
            field=models.CharField(blank=True, choices=[('piece', 'Piece'), ('bag', 'Bag'), ('metric_tonne', 'Metric Tonne'), ('kilogram', 'Kilogram'), ('cubic_foot', 'Cubic Foot'), ('square_foot', 'Square Foot'), ('cubic_meter', 'Cubic Meter'), ('meter', 'Meter'), ('set', 'Set'), ('litre', 'Litre'), ('foot', 'Foot'), ('bundle', 'Bundle'), ('square_meter', 'Square Meter')], max_length=555, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serviceregions',
            name='product',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_service_regions', to='app_inventory.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
