# Generated by Django 5.0 on 2024-01-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0004_rename_mpr_pricestructure_mrp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingdetails',
            name='pick_up_location',
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='pick_up_location',
            field=models.ManyToManyField(related_name='warehouse_pickup_location', to='app_inventory.pickupwarehouselocation'),
        ),
    ]
