# Generated by Django 5.0 on 2024-01-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0006_remove_product_hsn_code_pricestructure_hsn_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='value',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
