# Generated by Django 5.0 on 2024-01-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0008_alter_productvariant_name_alter_productvariant_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingdetails',
            name='pick_up_location',
            field=models.ManyToManyField(blank=True, null=True, related_name='warehouse_pickup_location', to='app_inventory.pickupwarehouselocation'),
        ),
    ]
