# Generated by Django 5.0 on 2024-01-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0009_alter_shippingdetails_pick_up_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingdetails',
            name='pick_up_location',
            field=models.ManyToManyField(related_name='warehouse_pickup_location', to='app_inventory.pickupwarehouselocation'),
        ),
    ]
