# Generated by Django 5.0 on 2024-01-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0010_alter_shippingdetails_pick_up_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='product_dimensions_unit',
            field=models.CharField(blank=True, choices=[('feet', 'Feet (ft)'), ('centimeters', 'Centimeters (cm)'), ('meters', 'Meters (mt)'), ('inches', 'Inches'), ('millimeters', 'Millimeters (mm)')], max_length=50, null=True),
        ),
    ]
