# Generated by Django 5.0 on 2024-01-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0011_product_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
