# Generated by Django 5.0 on 2024-01-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0014_alter_product_about_the_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricestructure',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
